apiVersion: apps/v1
kind: Deployment
metadata:
  name: one
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-application
  template:
    metadata:
      labels:
        app: my-application
      annotations:
        name: {{ .Files.Get "./configmap.yaml" | sha256sum }}
    spec:
      containers:
        - name: my-container
          image: nginx
          volumeMounts:
            - name: config-volume
              mountPath: /tmp/config
      volumes:
        - name: config-volume
          configMap:
            name: my-config
